services:
  db:
    image: postgres:15
    container_name: postgres-local
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
